spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PetCareBd
    username: postgres
    password: 2006
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
server:
  port: 3001
